spring.application.name=chatapp
# Replace the text after the equals sign with your actual OpenAI API Key
spring.ai.openai.api-key=sk-your-key-goes-here
spring.data.mongodb.uri=mongodb+srv://chat_app:chatapp123@cluster0.p4tyn.mongodb.net/chatapp_db?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# CRITICAL FOR RENDER: Use the dynamic port variable
server.port=${PORT:8080}
server.address=0.0.0.0

spring.main.allow-circular-references=true

# Logging (So you can see the OTPs in your IDE console for testing)
logging.level.com.prattle=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO
# Increases the number of simultaneous connections to Atlas
spring.data.mongodb.min-connections-per-host=5
spring.data.mongodb.max-connections-per-host=20

# Allow larger image uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB